# Generated by Django 3.2.3 on 2021-05-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzytkownik',
            name='autoryzacja',
            field=models.BooleanField(default=False),
        ),
    ]
