# Generated by Django 3.2.3 on 2021-05-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_wiadomosci_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wiadomosci',
            name='image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Obrazek: '),
        ),
    ]
